indexUrl=https://dsportalapp.herokuapp.com/
loginUrl=https://dsportalapp.herokuapp.com/login
homepageUrl=https://dsportalapp.herokuapp.com/home
registerUrl=https://dsportalapp.herokuapp.com/register
browser=CHROME
implicitWait=10
explicitWait=20
pageLoadTimeout=130
scriptTimeout=130
username=DreamTeam
password=Dre@mTe@m123

#general titles

indexPage=Numpy Ninja
homePage=NumpyNinja
loginPage=Login
resgisterPage=Registration
tryEditor=Assessment
practiceQuestions=Practice Questions
pythonCode1=search( [12, 23, 45, 67, 6, 90] , 12)
pythonCode2=search( [12, 23, 45, 67, 6, 90], 25)
pythonCode3=findMaxConsecutiveOnes([1, 0, 1, 1, 0, 1])
pythonCode4=findMaxConsecutiveOnes([1,1,0,1,1,1])
pythonCode5=findNumbers([12,345,2,6,7896])
pythonCode6=findNumbers([555,901,482,1771])
pythonCode7=sortedSquares([-7,-3,2,3,11])
pythonCode8=sortedSquares([-4,-1,0,3,10])
excelSheet=C:\Users\sange\eclipse-workspace\DsAlgodemo\src\test\resources\testData\Excel_Login_Pythoncode.xlsx
excelSheetNew=C:/Users/sange/Documents/NN/dsAlgo/dsAlgo_ExcelData.xlsx

#practice Questions Expected Outputs
searchArrayRunOutput1=Element Found
searchArrayRunOutput2=Not Found
#searchArrayRunOutput3=
maxConsecutiveRunOutput1=2
maxConsecutiveRunOutput2=3
#maxConsecutiveRunOutput3=
findNumbersRunOutput1=2
findNumbersRunOutput2=1
#findNumbersRunOutput3=
sortedArrayRunOutput1=[4, 9, 9, 49, 121]
sortedArrayRunOutput2=[0, 1, 9, 16, 100]
#sortedArrayRunOutput3=

searchArraySubmitOutput1=Some Tests failed. Please review code
#searchArraySubmitOutput2=Error occurred during submission
maxConsecutiveSubmitOutput1=Some Tests failed. Please review code
#maxConsecutiveSubmitOutput2=Error occurred during submission
findNumbersSubmitOutput1=Submission Successful
#findNumbersSubmitOutput2=Error occurred during submission
sortedArraySubmitOutput1=No tests were collected
#sortedArraySubmitOutput2=No tests were collected

#page titles

arrayPage=Array
arraysInPython=Arrays in Python
arraysUsingList=Arrays Using List
basicOperInList=Basic Operations in Lists
appOfArray=Applications of Array


#tryEditor
tryEdit_success=Hello
excelPath=C:/Users/sange/eclipse-workspace/DsAlgodemo/src/test/resources/testData/dsAlgo_ExcelData.xlsx
#signInPage_Exp_Title=NumpyNinja
#arrModPage_Exp_Title=Array
#arrAIPPage_Exp_Title=Arrays in Python
#arrAULPage_Exp_Title=Arrays Using List
#arrBOLPage_Exp_Title=Basic Operations in Lists
#arrAOAPage_Exp_Title=Applications of Array
#tryEditorPage_Exp_Title=Assessment
#pracQnsPage_Exp_Title=Practice Questions 



#url=https://dsportalapp.herokuapp.com/home
#arrModUrl=https://dsportalapp.herokuapp.com/array/
#arrAIPUrl=https://dsportalapp.herokuapp.com/array/arrays-in-python/
#arrAULUrl=https://dsportalapp.herokuapp.com/array/arrays-using-list/
#arrBOLUrl=https://dsportalapp.herokuapp.com/array/basic-operations-in-lists/
#arrAOAUrl=https://dsportalapp.herokuapp.com/array/applications-of-array/
#pracQnsUrl=https://dsportalapp.herokuapp.com/array/practice
#tryHereUrl=https://dsportalapp.herokuapp.com/tryEditor
#pracQnsUrl=https://dsportalapp.herokuapp.com/array/practice
#pracQn1Url=https://dsportalapp.herokuapp.com/question/1
#pracQn2Url=https://dsportalapp.herokuapp.com/question/2
#pracQn3Url=https://dsportalapp.herokuapp.com/question/3
#pracQn4Url=https://dsportalapp.herokuapp.com/question/4





